
services:
  www:
    depends_on:
      - db
    image: php:8.3.16-apache
    ports:
      #ports for your server 80 is the listner and 443 is for https 
      - 80:80
      - 443:443
    volumes:
      - ./www:/var/www/html
    command: "/bin/sh -c 'docker-php-ext-install mysqli && apache2-foreground'"
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: demo
      MYSQL_USER: demo
      MYSQL_PASSWORD: 123456
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - .db/:/docker-entrypoint-initdb.d
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest
    ports:
      - 81:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306

      
# use docker-compose up 
